package com.redudant.makanmen.view;

import android.view.Menu;

import com.redudant.makanmen.model.MenuMakanan;

import java.util.ArrayList;

public class MakananBetawi {

    public static String[][] data = new String[][]{
            {"Kerak Telor", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-1.jpg", "Kerak telor memiliki rasa gurih dan legit ini memang favorit warga Jakarta. Hidangan khas Betawi ini dibuat dari bahan-bahan makanan seperti, beras ketan putih, telur ayam atau bebek, ebi yang disangrai kering sampai menjadi serundeng, lalu ditambah bawang goreng, kemudian diberi bumbu halus seperti kelapa sangrai dan lainnya. Hal unik dari kuliner khas betawi ini adalah cara memasaknya. Telur dimasak ketika setengah matang akan dibalik wajannya menghadap panas arang dari anglo lalu dibiarkan seperti itu sampai matang sehingga menjadi kerak."},
            {"Nasi Uduk Betawi", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-2.jpg", "Nasi Uduk adalah kuliner khas Betawi lainnya. Proses memasak beras untuk nasi uduk adalah dengandiaron dengan menggunakan air santan, daun salam, daun jeruk, laos, dan serai lalu dikukus sampai matang. Rasanya gurih dan memiliki aromanya tersendiri.Nasi uduk Betawi biasanya disajikan dengan taburan bawang goreng, dengan lauk seperti ayam goreng, sambal dan pelengkap lainnya beserta daun kemangi."},
            {"Gado-gado Betawi", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-3.jpg", "Makanan tradisional betawi selanjutnya adalah gado-gado betawi. Gado-gado sendiri berarti campur aduk dalam bahasa Betawi adalah favorit masyarakat Betawi. Berbagai jenis sayur yang di rebus bersama kentang, tahu, tempe dan telur yang disiram dengan bumbu kacang dan taburan kerupuk menjadikan hidangan ini digemari banyak orang. Kuliner khas betawi ini sangat nikmat disantap dengan nasi atau disajikan bersama lontong."},
            {"Semur Jengkol", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-4.jpg", "Semur jengkol hidangan khas Betawi ini terkenal dengan bau nya. Untuk beberapa orang, bau jengkol dapat membuatnya tidak suka, tetapi untuk penggemar jengkol, hidangan ini sangatlah digemari. Masakan ini dimasak dengan jengkol yang memiliki rasa pahit, namun setelah dimasak menggunakan berbagai bumbu dan rempah, jengkol menjadi lezat untuk disantap. Semur jengkol biasanya disajikan dengan nasi putih atau nasi uduk hangat. Jangan lupa mencoba hidangan khas Betawi satu ini ya, kalau berkunjug ke Jakarta!"},
            {"Soto Betawi", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-5.jpg", "Soto betawi merupakan kuliner khas Betawi dari soto santan dengan isian daging sapi beserta jeroan dan organ sapi dan hewan lainnya seperti ayam. Banyak orang menggemari jenis soto khas Betawi ini. Penggemarnya tidak hanya orang di Jakarta, masyarakat lain di berbagai daerah di Indonesia juga gemar menyantap masakan khas Betawi ini. Soto Betawi memiliki rasa gurih yang berbeda dengan soto lainnya."},
            {"Roti Buaya", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-6.jpg", "Roti buaya memiliki peran penting dalam pernikahan adat Betawi. Kuliner khas betawi satu ini memiliki panjang sekitar 50 cm ini dibawa oleh mempelai laki-laki untuk diberikan kepada pengantin wanita di dalam pernikahan atau lamaran di pernikahan adat Betawi. Roti buaya ini memiliki makna tersendiri bagi warga Betawi, yaitu sebagai ungkapan kesetiaan pasangan menikah yang dipercaya masyarakat Betawi secara turun-temurun."},
            {"Asinan Betawi", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-7.jpg", "Asinan Betawi umumnya merupakan campuran dari sawi, kol, tauge, tahu putih dan selada yang ditaburi dengan kacang tanah goreng. Semua itu lalu disiram dengan kuah bumbu kacang serta dicampur cuka dan cabai dengan kerupuk mie besar berwarna kuning.Selain enak dan segar, makanan khas betawi ini juga tergolong sehat karena menggunakan banyak sayur-sayuran."},
            {"Kue Cucur", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-8.jpg", "Kue cucur adalah salah satu kue tradisional khas Betawi yang sering dan mudah kita jumpai di pasar tradisional maupun di toko kue. Kue ini juga dapat ditemui di tempat-tempat seperti di upacara pernikahan, potong rambut bayi dan lainnya. Kue cucur ini rasanya manis dengan tekstur lembut di bagian tengahnya, serta renyah di bagian pinggirnya. Kue berbahan dasar beras dan gula merah ini dimasak dengan cara digoreng. Termasuk salah satu makanan khas betawi wajib coba"},
            {"Dodol Betawi", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-9.jpg", "Betawi terkenal dodol dengan cita raalezat. Cara membuat camilan khas betawi dengan cara tradisional menggunakan kuali besar sangatlah unik dan menarik. Kuali yang bernama Kenceng ini berukuran diameter 50 cm sampai 1 meter. Dodol ini dibuat dari kelapa dan ketan menjadikanya lengket dan kenyal."},
            {"Putu Mayang", "ES", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-10.jpg", "Putu mayang adalah kue tradisional khas Betawi yang dibuat dari tepung kanji atau tepung beras  berbentuk seperti mie, dengan campuran santan kelapa, lalu disajikan dengan kinca atau gula jawa cair. Biasanya tepung beras diberi warna-warni agar menarik pembeli."},
            {"Kue Rangi", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-11.jpg", "Kue rangi adalah salah satu kue tradisional Betawi yang masih sering kita jumpai di berbagai tempat di Jakarta. Kue khas betawi dari campuran kelapa parut dan tepung sagu ini disajikan dengan saus gula merah yang menjadi kental dengan campuran sagu."},
            {"Kue Talam", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-12.jpg", "Kue talam adalah salah satu jenis camilan tradisional Betawi yang mudah ditemukan di mana saja di Indonesia. Kue ini dibuat dengan bahan baku tepung seperti tepung beras, tepung tapioka, tepung terigu atau tepung sagu."},
            {"Kue Cente Manis", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-13.jpg", "Kue cente adalah kue khas Betawi yang dibuat dengan bahan seperti tepung hunkwe, santan, gula, dan bulir cente manis atau sagu mutiara yang sudah matang. Kemudian bahan-bahan ini dibungkus dalam bungkus plastik lalu dikukus dan jadilah makanan khas betawi manis ini."},
            {"Getuk Lindri", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-14.jpg", "Getuk merupakan jenis makanan dengan bahan utama dari singkong. Getuk adalah makanan khas betawi yang sering dijumpai di daerah Jawa Tengah maupun Jawa Timur selain di Jakarta. Pengolahan getuk berawal dari singkong yang sudah dikupas, selanjutnya dikukus atau direbus. Lalu sesudah matang ditumbuk atau digiling, kemudian ditambahkan gula dan pewarna makanan. Untuk penyajian, getuk lindri biasanya diberikan taburan parutan kelapa."},
            {"Roti Gambang", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-15.jpg", "Roti gambang adalah roti tradisional khas Betawi berbahan dasar tepung terigu dan gula merah. Gula merah inilah yang menyebabkan roti ini memiliki warna coklat tanpa membutuhkan pewarna sintetis tambahan.Kuliner ini sangat cocok disajikan sebagai cemilan untuk keluarga karena rasanya manis dan lezat ."},
            {"Bir Pletok", "Minuman", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-16.jpg", "Kuliner Betawi satu ini adalah minuman khas Betawi. Bir pletok bukanlah bir biasa. Bir ini memiliki manfaat kesehatan dan tidak membuat mabuk karena tidak mengandung alkohol. Bir ini dibuat dengan bahan dasar rempah-rempah khas Indonesia dengan campuran jahe, daun pandan wangi serta serai. Untuk menarik pembeli, bir ini biasanya dicampur dengan tambahan kayu secang, yang akan membuat warna bir menjadi merah ketika ditambahkan dengan air panas."},
            {"Es Doger", "Minuman", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-17.jpg", "Es doger adalah minuman khas betawi lainnya yang merupakan campuran es dengan susu kelapa. Es ini dijual dengan cara gerobak dorong keliling di Jakarta, Bandung Malang, Surabaya dan kota-kota besar lainnya. Es doger biasanya disajikan dengan parutan kelapa, tape, ketan hitam, alpukat dan lain-lain."},
            {"Kue Pancong", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-18.jpg", "Kue pancong adalah camilan tradisional Betawi. Umumnya camilan khas Betawi ini bentuknya setengah lingkaran, dibuat dari santan, tepung besar, kelapa, dan garam. Kue ini biasanya dimakan di sore hari di samping teh hangat. Kue ini ditambah dengan potongan kelapa dan taburan gula pasir diatasnya."},
            {"Nasi Ulam", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-19.jpg", "Salah satu nasi khas Betawi yang semakin sulit ditemukan adalah nasi ulam. Nasi dengan beragam lauk sebagai pelengkap hidangan ini telah lama menjadi favorit masyarakat Betawi. Nasi ulam di sini disajikan dengan berbagai macam lauk seperti telur dadar, cumi, semur tempe, semur tahu, tempe goreng, perkedel dan dendeng."},
            {"Kue Ape", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-20.jpg", "Kue tradisional Betawi ini mirip dengan kue cucur pandan ini bernama kue ape. Kue ini memiliki tekstur garing dan renyah di bagian pinggirnya yang terbuat dari pandan sehingga berwarna hijau. Kue ape biasanya dijual dengan gerobak yang sering kita jumpai di pinggir jalan."},
            {"Soto Tangkar", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-21.jpg", "Soto tangkar adalah hidangan khas Betawi dan sekilas mirip dengan soto betawi. Kata “tangkar” berasal dari bahasa Betawi yang berarti iga. Soto khas betawi satu ini biasanya dinikmati saat cuaca dingin atau saat hujan dengan tambahan nasi dan sambal merah pedas."},
            {"Kembang Goyang", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-22.jpg", "Kue kembang goyang adalah jajanan tradisional Betawi yang sampai sekarang masih digemari masyarakat. Nama ‘kembang goyang’ berasal dari bentuknya yang menyerupai kelopak bunga atau kembang dan proses pembuatannya dengan cara digoyang-goyang hingga adonan terlepas dari cetakan. Kue kembang goyang dibuat dari bahan dasar tepung ketan yang sekarang sudah banyak varian rasa lainnya."},
            {"Selendang Mayang", "ES", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-23.jpg", "Adonan kue di dalam selendang mayang dibuat seprti agar-agar dengan warna-warni menarik. Warna-warna cantik ini seperti warnaselendang. Karenanya disebut ‘selendang mayang’. Adonan kue yang sudah dipotong-potong disajikan bersama dengan siraman sirup gula Jawa, kuah santan, dan potongan es batu."},
            {"Kue Lupis", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kue-lupis.jpg", "Kue lupis terbuat dari beras ketan yang dibuat dengan daun pisang dibalut seperti lemper atau lontong, lalu diiris tipis-tipis dan dicampur dengan parutan kelapa. Ditambah dengan gula aren kental yang dicairkan menjadi pelengkap kue lupis."},
            {"Ketupat/Lontong Sayur", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-25.jpg", "Lontong atau ketupat sayur adalah menu wajib di saat Idul Fitri. Ketupat sayur adalah ketupat yang disiram dengan kuah santan. Biasanya hidangan ini dimakan bersama dengan opor ayam, semur daging, dan makanan lainnya. Tidak lupa dengan taburan kerupuk bertekstur renyah."},
            {"Kue Geplak", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-26.jpg", "Kue geplak adalah kue kas betawi dari beras pera. Beras ini digiling hingga menjadi tepung yang kemudian disangrai. Lalu, setelah disangrai bahan ini dicampurkan dengan kelapa parutsangrai. Setelah itu adonan dicampur dengan gula pasir cair sampai kental. Selagi panas, adonan makanan khas Betawi ini harus diaduk sampai adonan padat."},
            {"Ketupat Babanci", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-27.jpg", "Ketupat babanci atau yang sering disebut dengan sayur babanci sebenarnya bukanlah sayur. Bahkan tidak ada sayurannya sama sekali. Nama babanci diambil dari si sayur ini sendiri yang tidak jelas usulnya karena tidak termasuk gule, kare ataupun soto. Maka itu disebut dengan ketupat babanci.  Ketupat babanci disajikan dengan daging kepala sapi. Selain daging kepala sapi, ditambahkan juga serutan kelapa srundeng yang ditumbuk halus."},
            {"Gabus Pucung", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-28.jpg", "Kuliner khas Betawi berbahan utama ikan gabus dan berkuah hitam pekat yang berasal dari pucung dengan campuran kluwak. Kuah pucung memang mirip kuah rawon tetapi memiliki tekstur berbeda. Makanan khas Betawi ini disajikan dengan ikan gabus yang digoreng dan disiram dengan kuah pucung."},
            {"Sengkulun", "Kue", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-29.jpg", "Kue sengkulun mirip dengan kue keranjang dengan permukaannya yang berbintil kasar, tekstur lunak, kenyal, dan lembut. Kue khas Betawi ini dibuat dengan tepung ketan dan gula merah dengan tambahan santan yang menjadikan rasanya gurih."},
            {"Sayur Besan", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-30.jpg", "Hidangan khas Betawi ini biasanya disajikan di pernikahan adat Betawi ini mirip dengan sayur lodeh, rasanya pun tidak jauh berbeda dari sayur lodeh. Kuahnya putih dan dengan banyak macam sayuran di dalamnya seperti kentang rebus, petai, daun bawang, bawang goreng dan cabai."},
            {"Bubur Ase", "Makanan", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-31.jpg", "Bubur ace berbeda dari bubur pada umumnya. Bubur nasi-nya biasa, tetapi topping yang di atasnya sangatlah berbeda. Bubur ini memiliki kuah gelap yang disebabkan oleh paudna dengan kuah semur daging khas Betawi. Ditambah dengan potongan daging sapi dan kentang dengan topping variasi lainnya."},
            {"Es Goyang", "ES", "https://ecs7.tokopedia.net/blog-tokopedia-com/uploads/2017/09/kuliner-betawi-32.jpg", "Es goyang adalah es khas Betawi dengan bahan-bahan sederhana seperti santan kelapa, gula pasir, perasa, dan tepung hunkue. Tepung hunkue merupakan tepung yang terbuat dari tumbukan kacang hijau. Variasi rasa es goyang antara lain adalah dengan tambahan buah seperti alpukat, durian, sampai coklat."}
    };

    public static ArrayList<MenuMakanan> getListmakanan() {
        ArrayList<MenuMakanan> list = new ArrayList<>();

        //for (String[] aMakanan : data) {
        for (String[] aMakanan : data) {
            MenuMakanan menuMakanan = new MenuMakanan();
            menuMakanan.setTitle(aMakanan[0]);
            menuMakanan.setSubtitle(aMakanan[1]);
            menuMakanan.setPhoto(aMakanan[2]);
            menuMakanan.setDesription(aMakanan[3]);

            list.add(menuMakanan);
        }

        return list;
    }
}
